<?php
class Error_Type{

	const FORM = "FORM";

	const DATA_BASE = "DATA_BASE";

	const SAME_USER_NAME="SAME_USER_NAME";

	const SAME_CATEGORY_NAME = "SAME CATEGORY NAME";

	const SAME_REGISTERED_DATA = "SAME REGISTERED DATA";

	const PRV_PASSWORD_DONT_MATCH = "PRV_PASSWORD_DONT_MATCH";

	const SAME_SECTOR_NAME = "SAME_SECTOR_NAME";

	const SAME_PRODUCT_TYPE_NAME = "SAME_PRODUCT_TYPE_NAME";

	const SAME_BID_NAME = "SAME_BID_NAME";

	const PASSWORD_DONT_MATCH = "PASSWORD_DONT_MATCH";


}